# Generated by Django 2.1.7 on 2019-03-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='Nombre del autor')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Apellido del autor')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('gender', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('OTRO', 'Otro')], max_length=10)),
                ('photo', models.ImageField(upload_to='autores')),
            ],
        ),
    ]
