run:
	@echo "------------------------> Reising Server <------------------------"
	python manage.py runserver

createuser:
	python manage.py createsuperuser --username=pyladies --email=pyladies@example.com


shell:
	python manage.py shell 



options:
	@echo
	@echo ----------------------------------------------------------------------
	@echo "   >>>>>                 Pyladies La Paz               <<<<<   "
	@echo ----------------------------------------------------------------------
	@echo
	@echo "   - superuser      Crear usuario"
	@echo "   - run            Levantar el servidor"
	@echo "   - shell          levantar la shell pytho"
	@echo
	@echo ----------------------------------------------------------------------
